sudo: required
addons:
  chrome: stable

language: node_js

node_js: 
  - 8.11.2

services:
  - mongodb

cache:
  directories:
  - node_modules

script:
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
